CREATE TABLE [dbo].[SupplierNote](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Created] [datetime2](7) NOT NULL,
	[Note] [varchar](max) NOT NULL,
	[SupplierID] [int] NOT NULL,
 CONSTRAINT [PK_Note] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SupplierNote]  WITH CHECK ADD  CONSTRAINT [FK_SupplierNote_Supplier] FOREIGN KEY([SupplierID])
REFERENCES [dbo].[Supplier] ([ID])
GO

ALTER TABLE [dbo].[SupplierNote] CHECK CONSTRAINT [FK_SupplierNote_Supplier]