//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace txo.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCommunication
    {
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public string Comment { get; set; }
        public int SupplierID { get; set; }
        public string ReasonForContact { get; set; }
        public byte ContactType { get; set; }
    
        public virtual ContactType ContactType1 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
